name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build (${{ matrix.label }})
    runs-on: ${{ matrix.os }}
    env:
      CI: true
      CSC_IDENTITY_AUTO_DISCOVERY: 'false'
      ELECTRON_SKIP_NOTARIZATION: 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            label: linux
            script: build:linux
            artifact: linux-artifacts
          - os: macos-latest
            label: macos
            script: build:mac
            artifact: macos-artifacts
          - os: windows-latest
            label: windows
            script: build:win
            artifact: windows-artifacts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm

      - name: Install system packages
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot rpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build distributables
        run: pnpm run ${{ matrix.script }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: release/**
          if-no-files-found: error
